CREATE TABLE HBTEST.COMPLAINT (ID int,COMPLAINT_DESCRIPTION varchar(500),PRIORITY INT ,
DEPARTMENT_TYPE INT,
USER_ID INT,
COMPLAINT_STATUS VARCHAR(200) ,
CRTD_TS DATE ,
UPDT_TS DATE ,
CRTD_BY VARCHAR(200));

CREATE TABLE HBTEST.USER(ID int,
NAME VARCHAR(200) ,
USER_TYPE INT ,
COMPLAINT_ID  INT,
ADDRESS VARCHAR(200) ,
USER_RELATIONSHIP VARCHAR(200) ,
IS_PRIME_USER VARCHAR(200) ) ;

CREATE TABLE HBTEST.COMPLAINT_ENGINEER_REL	
(COMPLAINT_ID INT , USER_ID INT)

CREATE TABLE HBTEST.USER_TYPE	
	
(ID INT , USER_TYPE VARCHAR(200));

CREATE TABLE HBTEST.DEPARTMENT_TYPE	(ID INT , DEPARTMENT VARCHAR(200));
